### ISSUE TITLE
SACS_receive(data, timeout)

### ISSUE THREAD

**Issue by Wakayo-Quozorox** [Wakayo-Quozorox/SACS#10]
Fonction de réception

Arguments : 
- data : pointeur vers un buffer pour stocker les donnés appli
- timeout : valeur en milliseconde du timeout à respecter

Valeur de retour : 
0 : OK
-1 : Timeout atteint

**Comment by hmnz** [comment]
- Ajouter un check du CRC avec la fonction `APP_SACS_checkCRC`
- Tester avc arduino
