### ISSUE TITLE
Créer une structure frameSACS pour gérer les envois de données

### ISSUE THREAD

**Issue by Wakayo-Quozorox** [Wakayo-Quozorox/SACS#16]
Définir une structure frameSACS pour faciliter le passage des données telles que l'ID, l'acknowledge, la data au travers d'un seul objet et pas de plusieurs arguments.

**Comment by hmnz** [comment]
OK, voir si pas meilleur moyen que de declarer caractere par caractère

**Comment by hmnz** [comment]
J'ai trouvé ça si jamais sur internet d'un mec qui avait exactement le même problème que nous @leilamedina @Wakayo-Quozorox :
```
One alternative is to create a temporary object, which you initialize, and then copy the contents of that temporary object into the target:

static const long temporary[] = { 1, 2, 3, 4, 5, 6 }; // Là tu met ton tableau direct
memcpy(test->mem, temporary, sizeof temporary); // Et ça ça te copie les valeurs de ton tableau dans ta structure
```
