### ISSUE TITLE
Vérifier la possibilité de modifier les variables

### ISSUE THREAD

**Issue by Wakayo-Quozorox** [Wakayo-Quozorox/SACS#19]
Vérifier s'il faut changer (ou pas) les variables appelées par certaines fonctions pour garantir leur non modifications par la fonction (const).
Je pense surtout aux fonctions send et checkCRC par exemple.

**Comment by hmnz** [comment]
Tout semble bien marcher du côté des const j'ai mis le max possible, je pull request
