### ISSUE TITLE
Main subordonné

### ISSUE THREAD

**Issue by MaxCau** [Wakayo-Quozorox/SACS#8]
Etablir la réaction du subordonné à la réception d'une requête du contrôleur : 
- Contrôler la réception de la trame requête
- Assigner réaction à la valeur de data
- Construire la trame retour
- Envoyer retour

**Comment by hmnz** [comment]
Se servir du code du contrôleur et l'adapter (voir #9)

**Comment by hmnz** [comment]
sacs receive cassé au niveau du print ou du remplissage #32

**Comment by hmnz** [comment]
@Wakayo-Quozorox on teste pour de bon demain et je ferme l'issue c'est ok ?

**Comment by hmnz** [comment]
Apres tests avec les deux cartes, j'ai l'impression que tout va bien y'a que des problèmes de timing j'ai l'impression donc je pull request le subordonne aussi. Par contre, ça necessite le correctif #40
